webtalk_init -webtalk_dir C:/Users/diego/Documents/Hardware Reconfigurable/ug-maestria-hr-pj-final/hr-proyecto-final/hr-proyecto-final.sim/sim_1/behav/xsim/xsim.dir/pj_final_testbench_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Oct  3 11:25:35 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2644227" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "cd25abc4-8cca-4f66-a734-dfe81a41f064" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "7483293c04834e8c8e63ea51c95d8058" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "21" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1800 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "2033370100 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "12.27_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "16176_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3707288163 -regid "" -xml C:/Users/diego/Documents/Hardware Reconfigurable/ug-maestria-hr-pj-final/hr-proyecto-final/hr-proyecto-final.sim/sim_1/behav/xsim/xsim.dir/pj_final_testbench_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/diego/Documents/Hardware Reconfigurable/ug-maestria-hr-pj-final/hr-proyecto-final/hr-proyecto-final.sim/sim_1/behav/xsim/xsim.dir/pj_final_testbench_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/diego/Documents/Hardware Reconfigurable/ug-maestria-hr-pj-final/hr-proyecto-final/hr-proyecto-final.sim/sim_1/behav/xsim/xsim.dir/pj_final_testbench_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
